creating
Borgc/big_bool pull request #1
Opened 2020-07-02 05:40 UTC by Borgc

2020-07-03 11:31 UTC, yalegko requested changes

2020-07-03 11:31 UTC, yalegko commented on CMakeLists.txt
> +add_executable(test bb_tests.c)
В CMake вроде можно делать отдельно цели для сборки и для тестов

2020-07-03 11:31 UTC, yalegko commented on bb_tests.c
> +        return 1;
При ошибке выполнения теста ни вектор ни строка не чистятся

2020-07-03 11:31 UTC, yalegko commented on bb_tests.c
> +        LOG_ERR("Wrong output from BB_right_shift (output != 000111000111)");
Лучше логгировать что именно пошло не так, чтобы сильно не думать при ошибке.

Типа `BB_right_shift: wrong for n < 8 (111000111000 >> 3 != 000111000111)`

2020-07-03 11:31 UTC, yalegko commented on bb_tests.c
> +    int count = 0;
`num_errors` было бы более говорящим названием

2020-07-03 11:31 UTC, yalegko commented on bb_tests.c
> +    }
А почему бы не сделать, если не полностью функцию сравнения векторов прям в библиотеке, то хотя бы тестовый хелпер, который превращает их в строки, сравнивает и чистит?

2020-07-03 11:31 UTC, yalegko commented on bb_tests.c
> +        }
`if(number <= 0){`

return? goto? default?

2020-07-03 12:22 UTC, Borgc commented on CMakeLists.txt
> +add_executable(test bb_tests.c)
Честно говоря, пока не знаю как

2020-07-03 12:43 UTC, Borgc commented on bb_tests.c
> +    }
Тесты таковы, что пишутся таким образом, как предполагается использовать библиотеку.
Если есть какой-то нормальный способ избавиться от функции BB_free(big_bool *bb) то я был бы не против сделать это.

2020-07-05 09:15 UTC, yalegko commented on CMakeLists.txt
> +add_executable(test bb_tests.c)
https://sysdev.me/cmake-and-ctest/

Примерно так:
```
enable_testing()
add_test(NAME BB_UnitTests COMMAND test)
```

2020-07-05 10:26 UTC, yalegko requested changes

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +}
На будущее: в таком варианте в Си очень легко потерять какой-нибудь free в if-е с ретёрном, поэтому лучше выставлять флаг/статус, а очистку производить в конце перед единственным ретёрном

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +}
И тут и в сдвигах нужны тесты с векторами разной длины: оба однобайтовые, один из большого числа байт, оба из большого, из целого числа байт и из нецелого

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +    if(strcmp(str, "10101010")){
Тоже напрашивается тест со случайными строками

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +    big_bool *rsh = BB_right_shift(vec2, num);
Тут очень не помешает комментарий. Надо быть достаточно внимательным читателем, чтобы сходу уловить связь между `num = 64` и `BB_from_uint64_t`. Сценарий таких хитрых тестов лучше помечать в комментах, чтобы экономить мыслетопливо читающего

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +}
Как-будто бы в 3 разных осмысленно названных функции они смотрелись бы попроще)

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +    }
Вообще, как пользователь, который на протяжении 300+ строк вынужден сравнивать вектор со строкой, я бы точно написал какую-нибудь функцию-хелпер)

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +}
Тоже выглядит какой-то безбожно длинной. Лучше стараться делать функции обозримыми. Если она не помещается на один экран -- что-то уже точно идёт не так

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +    string[BB_lenght(inv4)] = '\x00';
Прекрасно понимаю усталость от calloc/free, но если кто-нибудь решит тестироваться на векторах подлиннее, то можно очень легко поймать переполнение стека в это месте

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +    }
333-358 что-то совсем сложно для понимания для стороннего наблюдателя. `BB_make_equal_size` вообще выглядит как приватная функцию, зачем она может понадобиться пользователю и что тут тестируется?

2020-07-05 10:26 UTC, yalegko commented on bb_tests.c
> +    }
Я бы сделал это двумя разными тестами (прям на уровне исполняемых файлов). Сейчас как-то неинтуитивно получается

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +typedef struct big_bool big_bool;
Оно же и так тайпдефается в хедере

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        printf("BB_free: You are using NULL pointer in function\n");
Принтфы в библиотечных функциях недопустимы. 

Если очень хочется, можно использовать отключаемый макрос/функцию, но кажется, в большинстве случаев удобнее просто посмотреть документацию

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    }
memcpy работает существенно быстрее цикла

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    if(vector == NULL)return -1;
Имхо, здесь -1 достаточно, чтобы сообщить об ошибке и можно обойтись без errno, просто описав случай в документации.

`bb_errno` имеет смысл использовать, когда в функции несколько мест, которые могут пойти не так и тебе важно сообщить пользователю и только факт ошибки, но и её причину

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +}
а вот https://en.cppreference.com/w/c/numeric/math/pow наверняка лучше оптимизирована и писать ничего не нужно :)

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    int mask;
Не нужно скатываться в ANSI C

Половина переменных вполне может иметь меньшее время жизни

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        mask += (((power(2, 8) - 1) & bb->parts[bb->last_byte - i]) >> ost);
За возведение двойки в степень умножением у нас на кафедре раньше сразу незачёт без разговоров ставили

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        mask += (((power(2, 8) - 1) & bb->parts[bb->last_byte - i]) >> ost);
`+=` выглядит очень чужеродно в битовых операциях

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        mask += (((power(2, 8) - 1) & bb->parts[bb->last_byte - i]) >> ost);
Да и вообще имеет смысл черкнуть в комменте пару строк об алгоритме, какой-то он хитрый получился

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        }else{vector->parts[i] =((power(2,8-ost)-1)& bb->parts[bytes])<< ost;}
Какое-то супер-творческое форматирование, которое не согласуется ни с одним из стандартных coding style

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    }
Почему бы не позволить пользователю делать циклический сдвиг на отрицательную величину? Результат вполне себе определён

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    big_bool *bb3 = BB_right_shift(bb1, number);
Зачем bb1 и bb2, если свдиг и так не портит оригинал?

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        bb3->parts[i] += bb4->parts[i];
Почему тут `+=`?

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    return(bb3);
Скобки у return это как носки с сандалями

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +}
Я честно прочитал документацию, но так и не понял что за магия тут происходит и зачем здесь `BB_right_shift`

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +}
Почему половина функции это копипаста? Вполне можно обойтись без этого

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    vector->parts = realloc(vector->parts, (big_vec->last_byte + 1)*sizeof(uint8_t));
copy_vector + realloc какая-то лишняя аллокация. calloc+memcpy будут эффективнее

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        }
Реаллокация на каждый байт это какое-то издевательство над ОС. Стоит выбрать какое-нибудь стартовое значение размера и удваивать его, когда место заканчивается

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +            }
https://en.cppreference.com/w/c/memory/realloc

On failure, returns a null pointer. The original pointer ptr remains valid and may need to be deallocated with free() or realloc().

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +            }
Но вообще это какая-то жесть. Что мешает сразу выделить сколько надо? Длина строки известна

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    return bb;
Зачем его копировать перед ретёрном?

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +        j = j % 8;
Деление на степень двойки и остаток от него обычно оптимизируются компиляторами, так что простая итерация по строке выглядела бы на порядок проще

Итерация по всему и сразу в купе с ничего не говорящими именами итераторов просто ломает мозг.

Кроме того, я что-то сильно не уверен, что там должно быть `||`, что вызывает вопросы о качестве тестов

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +    big_bool vector = {(uint8_t *)calloc(9, sizeof(uint8_t)), 0, 8};
Лучше пользоваться именованными инициализаторами полей. Если изменится порядок/состав полей, то можно наловить кучу неприятных ошибок

2020-07-05 10:26 UTC, yalegko commented on big_bool.c
> +}
Зачем тут copy?

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> +    int last_byte;
`int` здесь чем-то оправдан?

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> + */
Ошибки лучше описывать в примечании к той функции, которые её возвращают

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> +// big_bool *BB_from_file(FILE *input_file);
Гит тем и хорош, что можно смело стирать старый мусорный код: он всегда останется в истории коммитов, откуда его при большом желании можно достать

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> +char *string_input();
Все функции в Си-библиотеках принятно называть с заданным префиксом

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> + *without making their size equal.
Это какая-то вымышленная проблема. Ведущие единицы никак не должны беспокоить пользователя, потому что находятся за last_bit

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> + * vector type of big_bool.
Ну свинство же заставлять пользователя так париться)

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> +big_bool *BB_right_shift(big_bool *bb, int number);
В каждой функции надо указать как понять что произошла ошибка и как понять какие были у неё причины

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> +big_bool *BB_cyclic_right_shift(big_bool *bb, int number);
> Behavior with number >= BB_lenght(bb) such a zero vector the same lenght 

неправда

2020-07-05 10:26 UTC, yalegko commented on big_bool.h
> +char *string_from_BB(big_bool *bb);
`BB_to_str` потому что нужно сохранять "префикс библиотеки"

2020-07-05 18:30 UTC, Borgc commented on bb_tests.c
> +    }
она и была приватной, пока я как раз не столкнулся с проблемой того, что без приведения длины равносильность не работает.
Подумал, что будет полезна

2020-07-05 18:30 UTC, Borgc commented on bb_tests.c
> +    }
Все это один из законов Де Моргана

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +    }
не знал о существовании такого

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +}
в самом деле, она так и не нашлась и навсега осталась для меня утерянной...

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +}
11111111=11111111
       1111=00001111= realloc + right shift, (только реаллок даст 11110000)
ведь младшие биты одного должны соответствовать младшим битам другого

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +}
что плохого в копипасте, который работает (я все писал сам)

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +    return bb;
а он вернется без этого?

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +        j = j % 8;
цикл работает, пока мы не приходим в так называемую "точку" (last_byte, last_bit)
сейчас сам понял, что прошляпил простую итерацию по строке

2020-07-05 18:30 UTC, Borgc commented on big_bool.h
> +big_bool *BB_cyclic_right_shift(big_bool *bb, int number);
oops

2020-07-05 18:30 UTC, Borgc commented on big_bool.h
> + *without making their size equal.
в нашем случае разговор про те, что спереди

2020-07-05 18:30 UTC, Borgc commented on big_bool.h
> + * vector type of big_bool.
как избавиться от этого не переписывая все?

2020-07-05 18:30 UTC, Borgc commented on big_bool.h
> +    int last_byte;
менять по надобности?

2020-07-05 18:30 UTC, Borgc commented on big_bool.c
> +}
чтобы можно было BB_free()?

2020-07-06 05:49 UTC, yalegko commented on big_bool.c
> +}
В том что любое изменение в одном месте повлечёт изменение и в скопированной части (или нет, если она была скопирована по делу и изменена)

Это серьёзный источник трудно находимых проблем и такого нужно избегать

2020-07-06 06:06 UTC, yalegko requested changes
Нужно:
- Убрать принты из библиотеки
- Убрать копипасту в операциях
- Убрать реаллокации из BB_from_string

2020-07-06 13:05 UTC, yalegko approved these changes

2020-07-07 09:49 UTC, merged